### ISSUE TITLE
Major Lag Issues - DEVELOPERS, PLEASE READ!

### ISSUE THREAD

**Issue by SharkFinPro** [SharkFinProductions/diepio-multiplayer#1]
More Than 1 Player Causes Serious Lag...I Need Help Finding The Source.

**Comment by Fantasy-Agario** [comment]
What handles the game logic ? Client or server ?

**Comment by SharkFinPro** [comment]
Server
Client Just Sends Data...
It might be sending too much data too fast...
need to find out if it is client or server lag :/

**Comment by Fantasy-Agario** [comment]
Yeah i think it might be overloading the server with too much data , 
The sever tries to catch up which causes lag in the client . 

But to reduce lag , you might wanna run the server on an IDE of some kind and have the clients connect to it , which would create a main public server . 

That server runs the logic 
= Still a bit laggy , but a lot more playable

**Comment by SharkFinPro** [comment]
@Fantasy-Agario A IDE or VPS wouldn't do anything differrent...
I Think The Lag Is the position of the barrel of the tanks :/
Im gonna try removing that and see if the lag goes away
^^Could You Do That? Im at school rn...plz test it
(im pretty sure the variable is "r"

**Comment by Fantasy-Agario** [comment]
Yh i'll test it , 
"I Think The Lag Is the position of the barrel of the tanks :/"
^^That's a pretty good point^^

**Comment by SharkFinPro** [comment]
Thanks.
bye The Way...If You Have Any Ideas For Labels, Feel Free To Add.
https://github.com/SharkFinProductions/diepio-multiplayer/labels

**Comment by Fantasy-Agario** [comment]
kk :)

**Comment by SharkFinPro** [comment]
@Fantasy-Agario If You Know Anyone That Can Code and would help us out, PM me on discord - I might be able to let them join **SFP**

**Comment by Fantasy-Agario** [comment]
Yeah ok , i might be able to find someone + i removed "r" and the game became a bit less laggy , but it still is 'laggy'

**Comment by SharkFinPro** [comment]
@Fantasy-Agario 
1. Is It more Laggy With 1 or 2 players?
2. If 2, then how did u test it? tabs next to each other, or behind and infront of each other

**Comment by Fantasy-Agario** [comment]
2 Players 
And Behind And Infront

**Comment by Fantasy-Agario** [comment]
BTW ,I edited some of the label colours + added some more :)

**Comment by Fantasy-Agario** [comment]
## Also about the VPS thing

I think a good VPS would help
Lets say we're making a game suited for multiple servers , for example Agar.io 

These games need a server to run the logic for each player,
If they didn't have a server and could run on a Localhost they would lagg 

Therefore  
If the logic gets handled by a VPS the game would be quicker / less laggier

**Comment by SharkFinPro** [comment]
@Fantasy-Agario Yes - A VPS could Help...
But Like Ogar Unimited, People can run the servers...Not everyone can afford a VPS, and they might want to run a private server...

Having it run from a computer with a core i7 and 8GB ram should be a good goal

**Comment by Fantasy-Agario** [comment]
Yes true , 
But you could have the choice of running the server on a VPS , 
But you don't have to , 

Also running it on a PC is not a bad idea :D

**Comment by SharkFinPro** [comment]
@Fantasy-Agario But then we would have to pay for other peoples servers.
Its not a good idea.
If they want their servers to be a VPS, They Can pay For It

**Comment by SharkFinPro** [comment]
@Fantasy-Agario Update Node To 7.0.0

**Comment by Fantasy-Agario** [comment]
kk :D

**Comment by SharkFinPro** [comment]
I Removed some lag bu tthere is still an insane amount with more than 1 player...but i brought it down quite a bit :/

https://github.com/SharkFinProductions/diepio-multiplayer/commit/d3255c0a1b29c94e380c44a1b2adb046b71b1368

**Comment by SharkFinPro** [comment]
This Line Really Helped...
https://github.com/SharkFinProductions/diepio-multiplayer/commit/d3255c0a1b29c94e380c44a1b2adb046b71b1368#diff-e6a5b42b2f7a26c840607370aed5301aR194

**Comment by Fantasy-Agario** [comment]
Ok that's good i'll try finding something else :)

**Comment by Fantasy-Agario** [comment]
Ok , 

# I found a Bug/Problem 

Lets say we have player 1 and player 2 

player 1 presses enter (to play)
Nothing happens 

player 2 presses enter 
The game loads .

**Comment by SharkFinPro** [comment]
@Fantasy-Agario I Know What you are talking about, and i realized the bug earlier today.
If you look into the console it says players[mynum] is not defined.
That would be in main.js i think, ill look into it now.

**Comment by SharkFinPro** [comment]
Also, @Fantasy-Agario Have you seen this yet?
https://github.com/SharkFinProductions/diepio-multiplayer/projects/1
I Would Like You to use it :D

**Comment by SharkFinPro** [comment]
Whelp
That was only on c9...
idk :/

CHAT LAG:
1 person: 2.5s
2 persons: 9.5s
^^
o_O

**Comment by SharkFinPro** [comment]
![capture](https://cloud.githubusercontent.com/assets/18649707/19746886/3e82afd8-9b8d-11e6-90bf-ec1a75415408.PNG)
Whelp
Look at the mem usage on it :/
Cpu is ded thanks to chrome XD

**Comment by Fantasy-Agario** [comment]
RIP CPU 6666 - 9999

You will be missed XD

**Comment by Fantasy-Agario** [comment]
+ I have seen it :D

**Comment by SharkFinPro** [comment]
i got it up to 1.5K+ mem usage :/
then it crashed

**Comment by Fantasy-Agario** [comment]
wow , thats pretty high , how'd u do it ?

**Comment by SharkFinPro** [comment]
first lots of tabs, then a tampermonkey bot script

**Comment by SharkFinPro** [comment]
OMG
FOUND THE MEMORY LEAK
//setInterval(updateEnemies, 0); //Calling This Makes Lag

**Comment by SharkFinPro** [comment]
Ill Commit now

**Comment by SharkFinPro** [comment]
its sending too much data...
Ill try seperating it soon

**Comment by Fantasy-Agario** [comment]
kk

**Comment by XtremePlayzCODE** [comment]
Looping a function 0 microseconds is dnagerously fast and can cause xtreme (look at my name) memory leaks

**Comment by SharkFinPro** [comment]
what should i loop it at instead? .-.

**Comment by XtremePlayzCODE** [comment]
For 60 FPS, do 1000 / 60 instead of 0, or do 100.

**Comment by SharkFinPro** [comment]
ok

**Comment by SharkFinPro** [comment]
Btw I Joined AJS-DEV

**Comment by XtremePlayzCODE** [comment]
CAN YOU UNBAN ME?!?!

**Comment by SharkFinPro** [comment]
From What

**Comment by SharkFinPro** [comment]
OgarUL? or Forums

**Comment by XtremePlayzCODE** [comment]
The orginization itself

**Comment by SharkFinPro** [comment]
ill see what i can do

**Comment by XtremePlayzCODE** [comment]
LegitSoulja banned me for being a good bug finder

**Comment by SharkFinPro** [comment]
.-.   ._.

**Comment by SharkFinPro** [comment]
oyeah i need ur help....
If you know anyone that would be good in SFP let me know, i may let them join

**Comment by SharkFinPro** [comment]
gtg

**Comment by SharkFinPro** [comment]
@XtremePlayzCODE I Have Just Tested It On 69 using 1000/60 and there is a signifigant decrease in lag.
I Will Test it on my computer when i get home and look at mem usage.

**Comment by XtremePlayzCODE** [comment]
Yes, you are welcome. I will close this issue now.

**Comment by XtremePlayzCODE** [comment]
Or not

**Comment by SharkFinPro** [comment]
@XtremePlayzCODE I Did not say it was fixed, i said i still need to test it.
Please leave this open

**Comment by XtremePlayzCODE** [comment]
Ok, just pushed commit, please check & revert if problems

**Comment by SharkFinPro** [comment]
ok

**Comment by SharkFinPro** [comment]
i cant check rn, but look at the comment i posted on it

**Comment by XtremePlayzCODE** [comment]
Should I revert?

**Comment by SharkFinPro** [comment]
yes

**Comment by SharkFinPro** [comment]
Ill do updates when i get home

**Comment by XtremePlayzCODE** [comment]
Ok, remove all pentagon, triangle, square updates on the whole file?

**Comment by SharkFinPro** [comment]
just revert please. I will do it when i get home

**Comment by XtremePlayzCODE** [comment]
ok

**Comment by SharkFinPro** [comment]
thx

**Comment by XtremePlayzCODE** [comment]
Pushed commit 'Revert'

**Comment by SharkFinPro** [comment]
k

**Comment by XtremePlayzCODE** [comment]
about how many hours, kinda wanna play some agar

**Comment by SharkFinPro** [comment]
3.5

**Comment by XtremePlayzCODE** [comment]
k 4:30 my time

**Comment by SharkFinPro** [comment]
k

**Comment by SharkFinPro** [comment]
probably around 2:50 ill be on PST

**Comment by XtremePlayzCODE** [comment]
your 2 hrs behind 20 ahead

**Comment by SharkFinPro** [comment]
?

**Comment by XtremePlayzCODE** [comment]
your 2 hrs behind and 20 minutes ahead iowa time

**Comment by SharkFinPro** [comment]
only 2 hours

**Comment by XtremePlayzCODE** [comment]
o ye

**Comment by SharkFinPro** [comment]
its 11:05 rn here

**Comment by XtremePlayzCODE** [comment]
oh wow

**Comment by XtremePlayzCODE** [comment]
yeah it is i checked google

**Comment by SharkFinPro** [comment]
gtg eat lunch, brb in a little over 30 min

**Comment by XtremePlayzCODE** [comment]
yeah u go

**Comment by SharkFinPro** [comment]
back

**Comment by XtremePlayzCODE** [comment]
ye sorry i was loking at extremely complicated node hello world programs

**Comment by SharkFinPro** [comment]
.-.
ok

**Comment by XtremePlayzCODE** [comment]
cant find any good ones XD

**Comment by SharkFinPro** [comment]
lol

**Comment by XtremePlayzCODE** [comment]
i just want something to have like 20 files...

**Comment by XtremePlayzCODE** [comment]
and then it prints out "Hi"

**Comment by SharkFinPro** [comment]
thats simple

**Comment by XtremePlayzCODE** [comment]
because my node program looks incredibly dumb without like 10 more files .-.

**Comment by SharkFinPro** [comment]
nah fam

**Comment by SharkFinPro** [comment]
:P

**Comment by XtremePlayzCODE** [comment]
wut do you meme?

**Comment by SharkFinPro** [comment]
no

**Comment by XtremePlayzCODE** [comment]
*queue justin beiber song*

**Comment by SharkFinPro** [comment]
.-.

._.

**Comment by XtremePlayzCODE** [comment]
what do you mean nah fam?

**Comment by SharkFinPro** [comment]
nevr mind ::P

**Comment by XtremePlayzCODE** [comment]
if i wanted complex programs i wouldn't go to you

**Comment by XtremePlayzCODE** [comment]
**THUG LIFE**

**Comment by SharkFinPro** [comment]
i can help u

**Comment by XtremePlayzCODE** [comment]
kk

**Comment by SharkFinPro** [comment]
just im learning Robot C In robotics right now :/

**Comment by XtremePlayzCODE** [comment]
dafuq?

**Comment by SharkFinPro** [comment]
lol school :P

**Comment by XtremePlayzCODE** [comment]
isn't that assembly, C for robots?

**Comment by XtremePlayzCODE** [comment]
XD or binary

**Comment by XtremePlayzCODE** [comment]
gotta love school selective classes

**Comment by SharkFinPro** [comment]
They Said Robot C :/
IDK THo...

**Comment by XtremePlayzCODE** [comment]
lol

**Comment by SharkFinPro** [comment]
The Thing That were using says ROBOTC in the top left corner

**Comment by XtremePlayzCODE** [comment]
http://www.robotc.net/

**Comment by XtremePlayzCODE** [comment]
programming language based on C

**Comment by SharkFinPro** [comment]
yes

**Comment by XtremePlayzCODE** [comment]
for robotics

**Comment by SharkFinPro** [comment]
btw im learning C++ AT home

**Comment by XtremePlayzCODE** [comment]
and I'm sitting here watching fuckin zootopia

**Comment by XtremePlayzCODE** [comment]
got nothing else better on netflix

**Comment by SharkFinPro** [comment]
hi i his partner

**Comment by SharkFinPro** [comment]
.-. lol

**Comment by XtremePlayzCODE** [comment]
UNLESS SEASON 2 OF STRANGER THINGS...

**Comment by SharkFinPro** [comment]
.-.

**Comment by XtremePlayzCODE** [comment]
no it's not out and won't be for a while .-.

**Comment by XtremePlayzCODE** [comment]
#jUSTICEFORBARB

WHAT WOULD WILL DO

**Comment by SharkFinPro** [comment]
lol

**Comment by XtremePlayzCODE** [comment]
PLEASE TELL ME THAT ELEVEN IS OK...

**Comment by SharkFinPro** [comment]
idk

**Comment by XtremePlayzCODE** [comment]
AND THE DEMOGORGAN IS GONE FOR GOOD....

**Comment by SharkFinPro** [comment]
lol

**Comment by XtremePlayzCODE** [comment]
*deleted*

**Comment by XtremePlayzCODE** [comment]
WUT...

**Comment by SharkFinPro** [comment]
ummm

**Comment by SharkFinPro** [comment]
hi

**Comment by XtremePlayzCODE** [comment]
https://github.com/SharkFinProductions/ComplexHelloWorld

**Comment by XtremePlayzCODE** [comment]
if you want to work on it

**Comment by SharkFinPro** [comment]
Ok

**Comment by XtremePlayzCODE** [comment]
kk

**Comment by XtremePlayzCODE** [comment]
i am seeing what i can do with the dart hello world XD

**Comment by XtremePlayzCODE** [comment]
100 kb

**Comment by XtremePlayzCODE** [comment]
`(function(){function a(d){d=Object.create(null);d.x=0;delete d.x;return d}function k(){}function c(d){function a(){}a.prototype=d;new a;return d}function b(){k.$isolateProperties=Object.create(null);b.allClasses=a();b.getTypeFromName=function(d){return b.allClasses[d]};b.interceptorsByTag=a();b.leafTags=a();b.finishedClasses=a();k.$finishIsolateConstructor=function(d){function a(){function a(){}for(var d=Object.keys(c),e=0;e<d.length;e++){var f=d[e];this[f]=c[f]}f=(d=b.lazies)?Object.keys(d):[];for(e=
0;e<f.length;e++)this[d[f[e]]]=null;a.prototype=this;new a;for(e=0;e<f.length;e++){var v=d[f[e]];this[v]=c[v]}}var c=d.$isolateProperties;a.prototype=d.prototype;a.prototype.constructor=a;a.$isolateProperties=c;a.functionThatReturnsNull=d.functionThatReturnsNull;return a}}(function(){var a=function(){};a.prototype={p:{}};var b=new a;if(!b.__proto__||b.__proto__.p!==a.prototype.p)return!1;try{if("undefined"!=typeof navigator&&"string"==typeof navigator.userAgent&&0<=navigator.userAgent.indexOf("Chrome/"))return!0;
if("function"==typeof version&&0==version.length){var c=version();if(/^\d+\.\d+\.\d+\.\d+$/.test(c))return!0}}catch(T){}return!1})();var w=a(),q=a(),r=a(),t=a(),A=a(),B=a(),C=a(),n=a(),D=a(),E=a(),F=a(),G=a(),H=a(),m=a(),I=a(),J=a(),K=a(),L=a(),M=a(),N=a(),O=a(),P=a(),Q=a(),R=a(),S=a();b();k.functionThatReturnsNull=function(){};(function(d,c){b.libraries||(b.libraries=[]);b.mangledNames||(b.mangledNames=a());b.mangledGlobalNames||(b.mangledGlobalNames=a());b.statics||(b.statics=a());b.typeInformation||
(b.typeInformation=a());b.globalFunctions||(b.globalFunctions=a());var k=b.libraries,v=b.mangledGlobalNames,m=d.length,e=a();e.collected=a();e.pending=a();e.constructorsList=[];e.combinedConstructorFunction="function $reflectable(fn){fn.$reflectable=1;return fn};\nvar $desc;\n";for(e=0;e<m;e++){var f=d[e],n=f[0],u=f[1],w=f[2],y=f[3],l=f[4],f=!!f[5],x=l&&l["^"];x instanceof Array&&(x=x[0]);for(var q=[],r=Object.keys(l),z=0;z<r.length;z++){var g=r[z];if("^"!==g){var h=l[g],t=g.charCodeAt(0),p;43===
t?(v[p]=g.substring(1),g=l[g],0<g&&(l[p].$reflectable=g),h&&h.length&&(b.typeInformation[p]=h)):42===t?(y[p].$defaultValues=h,h=l.$methodsWithOptionalArguments,h||(l.$methodsWithOptionalArguments=h={}),h[g]=p):"function"===typeof h&&(y[p=g]=h,q.push(g),b.globalFunctions[g]=h)}}k.push([n,u,[],q,w,x,f,y])}})([["dart2js._js_primitives","dart:_js_primitives",,n,{"^":"",printString:function(a){if("function"==typeof dartPrint)dartPrint(a);else if("object"==typeof console&&"undefined"!=typeof console.log)console.log(a);
else if("object"!=typeof window)if("function"==typeof print)print(a);else throw"Unable to print message: "+String(a);}}],["","l.dart",,m,{"^":"",main:function(){var a,b;for(a=0;4>a;++a)b="hello "+a,n.printString(b)}},1]],0);var u=k.$isolateProperties,u=null;b.isHunkLoaded=function(a){return!!$dart_deferred_initializers$[a]};b.deferredInitialized=Object(null);b.isHunkInitialized=function(a){return b.deferredInitialized[a]};b.initializeLoadedHunk=function(a){$dart_deferred_initializers$[a]($globals$,
u);b.deferredInitialized[a]=!0};b.deferredLibraryUris={};b.deferredLibraryHashes={};k=k.$finishIsolateConstructor(k);u=new k;b.metadata=[];b.types=[];w=c(w);q=c(q);r=c(r);t=c(t);A=c(A);B=c(B);C=c(C);n=c(n);D=c(D);E=c(E);F=c(F);G=c(G);H=c(H);m=c(m);I=c(I);J=c(J);K=c(K);L=c(L);M=c(M);N=c(N);O=c(O);P=c(P);Q=c(Q);R=c(R);S=c(S);(function(a){function b(d){for(var e=0;e<c.length;++e)c[e].removeEventListener("load",b,!1);a(d.target)}if("undefined"===typeof document)a(null);else if("undefined"!=typeof document.currentScript)a(document.currentScript);
else for(var c=document.scripts,d=0;d<c.length;++d)c[d].addEventListener("load",b,!1)})(function(a){b.currentScript=a;"function"===typeof dartMainRunner?dartMainRunner(m.main,[]):m.main([])})})();`

**Comment by SharkFinPro** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
except i want files

**Comment by XtremePlayzCODE** [comment]
so i'm trying to divide it into files

**Comment by SharkFinPro** [comment]
plz create an src folder for all of the stuf fot go into

**Comment by XtremePlayzCODE** [comment]
its chw

**Comment by XtremePlayzCODE** [comment]
folder

**Comment by SharkFinPro** [comment]
change it to src

**Comment by XtremePlayzCODE** [comment]
sure

**Comment by XtremePlayzCODE** [comment]
Pushed commit 'k'

**Comment by SharkFinPro** [comment]
k

**Comment by SharkFinPro** [comment]
u there?

**Comment by XtremePlayzCODE** [comment]
yes

**Comment by SharkFinPro** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
just coding github.com/Xenirus

**Comment by SharkFinPro** [comment]
Ok

**Comment by SharkFinPro** [comment]
I Need Help...Need TO Recode All The Tanks

**Comment by SharkFinPro** [comment]
.-.

**Comment by XtremePlayzCODE** [comment]
i can do it

**Comment by SharkFinPro** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
and p.s, could we possibly use Tini for diep?

**Comment by XtremePlayzCODE** [comment]
and how can i rewrite it? whats wrong with it?

**Comment by SharkFinPro** [comment]
Yes, THats What i was planning on

**Comment by XtremePlayzCODE** [comment]
so rewrite it for tini?

**Comment by SharkFinPro** [comment]
TIni Not Gonna IMplement yet

**Comment by XtremePlayzCODE** [comment]
ok whats wrong with the tanks

**Comment by SharkFinPro** [comment]
you will be able to choose between tini or pjs

**Comment by XtremePlayzCODE** [comment]
WHATS WRONG WITH THE TANKS

**Comment by SharkFinPro** [comment]
they werent scaled properly, and they need a redo on code as i have changed the format

**Comment by XtremePlayzCODE** [comment]
so increase size

**Comment by XtremePlayzCODE** [comment]
a redo on code? like indentation?

**Comment by SharkFinPro** [comment]
increase size, and change the format

**Comment by XtremePlayzCODE** [comment]
redo indentation?????

**Comment by SharkFinPro** [comment]
there is no longer a player object

**Comment by XtremePlayzCODE** [comment]
on multiplayer or ?

**Comment by SharkFinPro** [comment]
just do it in the...for loop .-.

**Comment by SharkFinPro** [comment]
im tingking we should do images tho

**Comment by XtremePlayzCODE** [comment]
what?

**Comment by SharkFinPro** [comment]
just as an object

**Comment by XtremePlayzCODE** [comment]
dude... on multiplayer or original?

**Comment by SharkFinPro** [comment]
multiplayer...ill link u to what i want u to do

**Comment by XtremePlayzCODE** [comment]
so we can't rely on player objects now?

**Comment by SharkFinPro** [comment]
no

**Comment by XtremePlayzCODE** [comment]
it will break everything... `switch(player.type){ case'twin':TWIN CODE;break;}`

**Comment by SharkFinPro** [comment]
just an object

**Comment by SharkFinPro** [comment]
so it wont break everything

**Comment by XtremePlayzCODE** [comment]
`switch (object.type) {case'twin'....}`

**Comment by SharkFinPro** [comment]
make tanks using this format
https://www.khanacademy.org/computer-programming/spin-off-of-new-program/5020607602
Then just display them as images
To Reduce lag

**Comment by XtremePlayzCODE** [comment]
can't display as image buddy

**Comment by SharkFinPro** [comment]
wai

**Comment by XtremePlayzCODE** [comment]
not that experienced in Processing

**Comment by XtremePlayzCODE** [comment]
but events and modeling i can do

**Comment by SharkFinPro** [comment]
gtg do work.
BRB in min of 30 min

**Comment by XtremePlayzCODE** [comment]
you get to work, i will rescale tank size

**Comment by XtremePlayzCODE** [comment]
or not

**Comment by XtremePlayzCODE** [comment]
wait yes i can

**Comment by SharkFinPro** [comment]
im here

**Comment by XtremePlayzCODE** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
you out yet?

**Comment by SharkFinPro** [comment]
ill be ready to code in about 45 min

**Comment by SharkFinPro** [comment]
i get out at 2:20, its 2:10right now

**Comment by XtremePlayzCODE** [comment]
ok, i am working on a clone of multiogar with minions

**Comment by SharkFinPro** [comment]
ill be ready at 2:50

**Comment by XtremePlayzCODE** [comment]
or 5 for me

**Comment by SharkFinPro** [comment]
k

**Comment by XtremePlayzCODE** [comment]
well 4:50

**Comment by SharkFinPro** [comment]
go to discord plz

**Comment by SharkFinPro** [comment]
**# I WILL BE CLOSING THIS ISSUE AFTER MY NEXT COMMIT, AS IT IS NOT FIXED YET.**

**Comment by Fantasy-Agario** [comment]
kk  :)

**Comment by SharkFinPro** [comment]
omg im gonna edit, or delete every file

**Comment by SharkFinPro** [comment]
Everything is Good Now Hopefully :D

**Comment by LegitSoulja** [comment]
Hm, @SharkFinPro Just so you know you'll never have owners permissions with AJS. When people get banned it's permanent!. There's no "I'll see what I can do". That kid needs to learn how to behave.

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE and please keep my name out your mouth. I don't know you, nor couldn't even care for you. 

You got banned for multiple reasons, the main reason was you kept trying to force me to make bots for you that I could care less about. I don't tolerate it, and neither does our community.

**Comment by SharkFinPro** [comment]
ok
