### ISSUE TITLE
Level command [RECOMMENDATION]

### ISSUE THREAD

**Issue by XtremePlayzCODE** [SharkFinProductions/diepio-multiplayer#2]
This should be easy to implement. Get the player, set the level, and boom.

**Comment by SharkFinPro** [comment]
yes

**Comment by XtremePlayzCODE** [comment]
Did you implement an array of players on the core server handler, it should be easy to do level and player list command

**Comment by SharkFinPro** [comment]
?

**Comment by XtremePlayzCODE** [comment]
Did you put an array of all players on the server in the main serverncontroller

**Comment by SharkFinPro** [comment]
src/core/playerServer.js
yes

**Comment by XtremePlayzCODE** [comment]
Good you can take an argument that has the player id, access the player in that array, and set the level for level command.

Use a for each loop, and for each player, print out the name, levels, etc.

**Comment by SharkFinPro** [comment]
yes, I Can Do that.
BTW Did you see the new commands thing? Feel Free To Add More...

**Comment by XtremePlayzCODE** [comment]
Yes, but I am staying home from school sick with no PC. Sent from my iPhone

**Comment by SharkFinPro** [comment]
ok.

**Comment by SharkFinPro** [comment]
gtg

**Comment by XtremePlayzCODE** [comment]
You, me, discord, now

**Comment by SharkFinPro** [comment]
.-.

**Comment by SharkFinPro** [comment]
Because I Am Planning On Adding A Level Command In The Future, I Am Closing This Issue Now.

**Comment by XtremePlayzCODE** [comment]
Don't think that Andrews meant to reference this issue in that PR
