### ISSUE TITLE
Tank barrel points at bots when it gets in bot's radius (src/ai/bot.js)

### ISSUE THREAD

**Issue by SharkFinPro** [SharkFinProductions/diepio-multiplayer#6]
No clue why this happens... looking into it now
If anyone finds the reason, please reply here :)

**Comment by Ciao121** [comment]
It only happens if the addbot command is executed after the browser open the game page. If the server is launched, the addbot command is executed and finally the browser open the page, it does not happens.  But now if the addbot command is executed another time the problem is present.

**Comment by SharkFinPro** [comment]
Thanks for the info! ill be using that to fix it

**Comment by SharkFinPro** [comment]
hmmm...even if the addbot is executed before, and it works, then i add a few more bots...all of them break.
so its probably not a creation bug

**Comment by SharkFinPro** [comment]
fixed
https://github.com/SharkFinProductions/diepio-multiplayer/commit/500686ea85d1cccd72150034aafb02a569efb5b2
