### ISSUE TITLE
The recent release seems not run well.

### ISSUE THREAD

**Issue by a632283395** [SharkFinProductions/diepio-multiplayer#7]
I tired to use different browsers and laptops, however the Server and Client were not run well.
When I press 'Enter', there is not any response including console logs showed on my chrome.
When I changed to another laptop, 'Enter' works, but still can not be played including none-movement and none-levels up.
Im not sure ur program is done yet. But, good luck to u.

**Comment by SharkFinPro** [comment]
@a632283395 by release, i think you mean commit, and i have been messing around with stuff atm, and probably am going to redo most of the client and make it wayy faster and better =)

**Comment by SharkFinPro** [comment]
Bye the way, the server is fine - just it seems to only work 100% on chrome for me. Edge is unplayable

**Comment by SharkFinPro** [comment]
Also, there is no leveling up yet :P
