### ISSUE TITLE
dosen't work

### ISSUE THREAD

**Issue by Faris90** [SharkFinProductions/diepio-multiplayer#8]
It does an error when I run it

**Comment by SharkFinPro** [comment]
What’s the error? (Sorry for late response)

**Comment by Faris90** [comment]
when I start it stops and gives an error in the console

**Comment by SharkFinPro** [comment]
Did u install npm modules?

**Comment by Faris90** [comment]
yes but:
Error: channel closed
    at process.target.send (internal/child_process.js:554:16)
    at Timeout.updates [as _onTimeout] (/home/ubuntu/workspace/src/core/enemyServer.js:88:13)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by SharkFinPro** [comment]
hmm

**Comment by SharkFinPro** [comment]
@Faris90 how are you attempting to run this?

**Comment by SharkFinPro** [comment]
whoops i really didnt see this! sorry!
uhm... is this off your computer or a vm

**Comment by Faris90** [comment]
what can I use other than c9

**Comment by SharkFinPro** [comment]
your computer.
add me on discord if you need help. SharkFin#0936

**Comment by SharkFinPro** [comment]
by the way, i'm working on v2 of this clone :)

**Comment by SuperOP535** [comment]
Yay!

**Comment by Faris90** [comment]
know any vps hoster

**Comment by SharkFinPro** [comment]
new version in development: https://github.com/SharkFinPro/diep-clone
